# Generated by Django 5.2.15 on 2026-07-02 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('single', 'По одному (radio)'), ('multiple', 'Несколько (checkbox)'), ('textarea', 'Свободный текст')], default='single', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.questionblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_embedding', models.JSONField(blank=True, editable=False, null=True)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_sessions', to='employees.employee')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('start', 'Survey start'), ('submit', 'Survey submit')], default='start', max_length=10)),
                ('success', models.BooleanField()),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_face_logs', to='employees.employee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_logs', to='surveys.surveysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin_conducted', models.BooleanField(default=False)),
                ('is_after_application', models.BooleanField(default=False)),
                ('after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('test_days_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('test_days_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_after_application', False), ('after_days__isnull', False), _connector='OR'), name='after_days_required_when_after_application')],
            },
        ),
        migrations.AddField(
            model_name='surveysession',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='surveys.test'),
        ),
        migrations.AddField(
            model_name='questionblock',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='surveys.test'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_option_ids', models.JSONField(blank=True, default=list)),
                ('text_value', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveysession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'question'), name='unique_session_question')],
            },
        ),
    ]
