# Locomotive Depot — developer task runner.
# Wraps the commands documented in README.md. Run `make` (or `make help`) for the list.

# --- Paths & tools ---------------------------------------------------------
BACKEND  := backend
FRONTEND := frontend
VENV     := $(BACKEND)/.venv
PY       := $(VENV)/bin/python
PIP      := $(VENV)/bin/pip
RUFF     := $(VENV)/bin/ruff
MANAGE   := $(PY) $(BACKEND)/manage.py
COMPOSE  := docker compose

.DEFAULT_GOAL := help

# Use bash so `trap`/`wait` in the `dev` target behave predictably.
SHELL := /bin/bash

##@ Help

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage: make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z0-9_-]+:.*?##/ { printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(MAKEFILE_LIST)
	@echo ""

##@ Setup

.PHONY: setup
setup: env install db-up migrate seed ## One-shot: env files, deps, Postgres, migrate, seed accounts
	@echo "✓ Setup complete. Run 'make dev' to start backend + frontend."

.PHONY: install
install: install-backend install-frontend ## Install backend + frontend dependencies

.PHONY: install-backend
install-backend: $(VENV) ## Create the venv and install backend dev requirements

$(VENV):
	python3 -m venv $(VENV)
	$(PIP) install --upgrade pip
	$(PIP) install -r $(BACKEND)/requirements/dev.txt

.PHONY: install-frontend
install-frontend: ## Install frontend npm dependencies
	cd $(FRONTEND) && npm install

.PHONY: env
env: ## Create backend/.env and frontend/.env from the examples (if missing)
	@test -f $(BACKEND)/.env  || (cp $(BACKEND)/.env.example  $(BACKEND)/.env  && echo "created $(BACKEND)/.env")
	@test -f $(FRONTEND)/.env || (cp $(FRONTEND)/.env.example $(FRONTEND)/.env && echo "created $(FRONTEND)/.env")
	@echo "ℹ Local backend reads DATABASE_URL from $(BACKEND)/.env (docker Postgres is on host port 5433)."

##@ Run

.PHONY: dev
dev: ## Run backend (:8000) and frontend (:3000) together; Ctrl-C stops both
	@echo "▶ backend → http://127.0.0.1:8000   frontend → http://localhost:3000"
	@trap 'kill 0' EXIT; \
		$(MANAGE) runserver & \
		( cd $(FRONTEND) && npm start ) & \
		wait

.PHONY: run-backend
run-backend: ## Start the Django dev server on :8000
	$(MANAGE) runserver

.PHONY: run-frontend
run-frontend: ## Start the React dev server on :3000
	cd $(FRONTEND) && npm start

##@ Database & data

.PHONY: migrate
migrate: ## Apply Django migrations
	$(MANAGE) migrate

.PHONY: makemigrations
makemigrations: ## Generate Django migrations from model changes
	$(MANAGE) makemigrations

.PHONY: seed
seed: ## Seed specialties + admin/medic/specialist accounts
	$(MANAGE) seed_initial_data

.PHONY: seed-demo
seed-demo: ## Seed demo data (question audio is generated by the Question post_save signal)
	$(MANAGE) seed_demo_data

.PHONY: superuser
superuser: ## Create a Django superuser interactively
	$(MANAGE) createsuperuser

.PHONY: shell
shell: ## Open the Django shell
	$(MANAGE) shell

##@ Quality

.PHONY: test
test: ## Run the backend test suite (pytest)
	cd $(BACKEND) && .venv/bin/python -m pytest

.PHONY: lint
lint: lint-backend lint-frontend ## Lint backend (ruff) and frontend (eslint)

.PHONY: lint-backend
lint-backend: ## Ruff check on the backend
	cd $(BACKEND) && .venv/bin/ruff check .

.PHONY: lint-fix
lint-fix: ## Ruff autofix on the backend
	cd $(BACKEND) && .venv/bin/ruff check --fix .

.PHONY: lint-frontend
lint-frontend: ## ESLint on the frontend
	cd $(FRONTEND) && npm run lint

.PHONY: typecheck
typecheck: ## TypeScript type-check the frontend (no emit)
	cd $(FRONTEND) && npx tsc --noEmit

.PHONY: build-frontend
build-frontend: ## Production build of the frontend
	cd $(FRONTEND) && npm run build

##@ Docker (full stack)

.PHONY: db-up
db-up: ## Start the Postgres container (host port 5433), wait until healthy
	$(COMPOSE) up -d --wait db

.PHONY: db-down
db-down: ## Stop the Postgres container
	$(COMPOSE) stop db

.PHONY: build
build: ## Build all Docker images (backend + frontend)
	$(COMPOSE) build

.PHONY: up
up: ## Build & start the whole stack (db + backend + frontend) in Docker
	$(COMPOSE) up --build

.PHONY: down
down: ## Stop and remove all Docker containers
	$(COMPOSE) down

.PHONY: logs
logs: ## Tail Docker logs for all services
	$(COMPOSE) logs -f

##@ Housekeeping

.PHONY: clean
clean: ## Remove the venv, frontend build, and node_modules
	rm -rf $(VENV) $(FRONTEND)/build $(FRONTEND)/node_modules
