server {
    listen 80;
    server_name lokomotiv-decor.uz www.lokomotiv-decor.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
