# Generated by Django 5.2.15 on 2026-06-11 13:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('bp_diastolic', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('pulse', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)])),
                ('saturation', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Oxygen saturation, %')),
                ('alcohol_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('alcohol_positive', models.BooleanField(default=False)),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('hours_rested', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('conclusion', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_checks', to='employees.employee')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_checks_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCheckAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=10)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='medical.medicalcheck')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
