# Generated by Django 5.2.15 on 2026-07-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
