# Generated by Django 5.2.15 on 2026-06-11 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='face_verification_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('specialty', 'Professional knowledge'), ('tech_safety', 'Technical safety'), ('industrial_safety', 'Industrial safety')], max_length=20)),
                ('text', models.TextField()),
                ('options', models.JSONField(help_text='List of exactly 4 answer options.')),
                ('correct_option', models.PositiveSmallIntegerField(help_text='Index 0-3 of the correct option.')),
                ('source', models.CharField(choices=[('ai', 'AI generated'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Not approved'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='employees.specialty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('specialty', 'Professional knowledge'), ('tech_safety', 'Technical safety'), ('industrial_safety', 'Industrial safety')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total', models.PositiveSmallIntegerField()),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_sessions', to='employees.employee')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_sessions', to='employees.specialty')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.testsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('correct_option__lte', 3)), name='question_correct_option_range'),
        ),
        migrations.AddConstraint(
            model_name='testanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_session_question'),
        ),
    ]
