# Generated by Django 5.2.15 on 2026-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='question_audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_text_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
