# Generated by Django 5.2.15 on 2026-06-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_question_audio_question_audio_text_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverificationlog',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_verification_logs', to='assessments.testsession'),
        ),
        migrations.AddField(
            model_name='faceverificationlog',
            name='stage',
            field=models.CharField(choices=[('start', 'Test start'), ('submit', 'Test submit')], default='start', max_length=10),
        ),
        migrations.AddField(
            model_name='testsession',
            name='face_embedding_model_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='testsession',
            name='face_embedding_snapshot',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='submit_face_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
