# Generated by Django 5.2.4 on 2026-06-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_faceverificationlog_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_status',
            field=models.CharField(choices=[('not_run', 'Not Run'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='not_run', max_length=20),
        ),
    ]
