# Generated by Django 5.2.15 on 2026-06-11 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='instructions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt', 'md'])])),
                ('generation_status', models.CharField(choices=[('not_started', 'Not started'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructions', to='employees.specialty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
